name: build

on:
  schedule:
    - cron:  '1 1 * * *'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'main'

      - name: Prepare
        run: |
          sudo apt-get -q update
          sudo apt install rename
          mkdir Rel
          touch ./Rel/.nojekyll
          cp ./feed/* ./Rel/
      - name: Fetch additional IPKs
        run: |
          TMPDIR=$(mktemp -d)
          git clone --depth 1 https://github.com/oe-alliance/picon-packages.git "$TMPDIR"
          find "$TMPDIR" -type f -name '*.ipk' -exec cp {} ./Rel/ \;
          rm -rf "$TMPDIR"
      - name: Fetch openpicons
        run: |
          cd ./Rel/
          PAGE="https://openpicons.com/?dir=full-motor-snp/ipk"
          curl -s "$PAGE" | \
            grep -oP '(?<=href=")\?file=[^"]+\.ipk' | \
            grep -v "800x450" | \
            while read -r RELATIVE_URL; do
              FILE_URL="https://openpicons.com/${RELATIVE_URL}"
              wget -c -nv --content-disposition "$FILE_URL"
            done
          PAGE="https://openpicons.com/?dir=full-motor-srp/ipk"
          curl -s "$PAGE" | \
            grep -oP '(?<=href=")\?file=[^"]+\.ipk' | \
            grep -v "800x450" | \
            while read -r RELATIVE_URL; do
              FILE_URL="https://openpicons.com/${RELATIVE_URL}"
              wget -c -nv --content-disposition "$FILE_URL"
            done
      - name: make index
        run: |
          cd ./Rel
          rename 'y/A-Z/a-z/' ./Rel/*.ipk
          find . -name '*.ipk' -size +98M | xargs rm -f
          chmod 755 ipkg-make-index.sh
          ./ipkg-make-index.sh
          rm ipkg-make-index.sh

      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./Rel
          force_orphan: true
