name: build

on:
  schedule:
    - cron:  '1 1 * * *'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'main'

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build
        run: |
          sudo apt-get -q update
          sudo apt install rename
          mkdir Rel
          touch ./Rel/.nojekyll
          cp ./feed/* ./Rel/
          cd ./Rel/
          wget -c -nH -r -q -l0 -A ipk -np -nd --wait=3 --execute="robots = off" --reject="*.800x450*" https://openpicons.com/picons/?dir=full-motor-snp
          wget -c -nH -r -q -l0 -A ipk -np -nd --wait=3 --execute="robots = off" --reject="*.800x450*" https://openpicons.com/picons/?dir=full-motor-srp
          rename 'y/A-Z/a-z/' *.ipk
          find . -name '*.ipk' -size +98M | xargs rm -f
          chmod 755 IPKFeedGenerator.jar
          chmod 755 ipkg-make-index.sh
          java -jar IPKFeedGenerator.jar
          ./ipkg-make-index.sh
          rm IPKFeedGenerator.jar
          rm ipkg-make-index.sh

      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./Rel
          force_orphan: true
